assignment/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('project_manager.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_manager/urls.py
from django.urls import path

from . import views

app_name = 'project_manager'
urlpatterns = [
    path('', views.ProjectListView.as_view(), name='index'),
    path('new_entry', views.CreateProjectView.as_view(), name='create_project'),
    path('<int:project_id>/project_detail',views.DetailProjectView.as_view(), name='project_detail'),
    path('<int:project_id>/edit',views.EditProjectView.as_view(), name='edit_project'),
    path('<int:project_id>/delete',views.DeleteProjectView.as_view(), name='delete_project'),
    path('new_task', views.CreateTaskView.as_view(), name='create_task'),
    path('<int:project_id>/<int:task_id>/edit_task',views.EditTaskView.as_view(), name='edit_task'),
    path('<int:project_id>/<int:task_id>/delete_task',views.DeleteTaskView.as_view(), name='delete_task'),
]

project_manager/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models

from django.db import models
from django.forms import ModelForm, ModelChoiceField
from django import forms
from django.contrib.admin import widgets  
from bootstrap_datepicker_plus import DatePickerInput, DateTimePickerInput

class Project(models.Model):
    project_name = models.CharField(max_length=200)
    description  = models.TextField()
    create_date  = models.DateTimeField('date create')
    avatar       = models.ImageField() 

    def __str__(self):
        return self.project_name

    def was_published_recently(self):
        return self.create_date >= timezone.now() - datetime.timedelta(days=1)

class Task(models.Model):
    title       = models.CharField(max_length=100)
    description = models.TextField()
    start_date  = models.DateField('date start')
    end_date    = models.DateField('date end')
    project     = models.ForeignKey(Project, on_delete=models.CASCADE)
    # assignee    = models.ForeignKey(
    #                 settings.AUTH_USER_MODEL,
    #                 on_delete=models.CASCADE,
    #             )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

#..> forms.py

class ProjectCreateForm(ModelForm):
    project_name = forms.CharField(label='Project name',
                           max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Project
        fields = ['project_name', 'description','create_date','avatar']  
        widgets = {
            'create_date': DatePickerInput(options={
                    "format": "MM/DD/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True
                })
        }

    def __init__(self, *args, **kwargs):
        super(ProjectCreateForm, self).__init__(*args, **kwargs)
        self.fields["avatar"].required = True
        

class TaskCreateForm(ModelForm):
    title = forms.CharField(label='Task name',
                           max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.TextInput()
    class Meta:
        model  = Task
        fields = ['title', 'description', 'start_date','end_date','project']  
        widgets = {
            'start_date': DatePickerInput(options={
                    "format": "MM/DD/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }), # default date-format %m/%d/%Y will be used
            'end_date': DatePickerInput(options={
                    "format": "MM/DD/YYYY", # moment date-time format
                    "showClose": True,
                    "showClear": True,
                    "showTodayButton": True,
                }), # specify date-frmat
        }


    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        project = ModelChoiceField(queryset=Project.objects.all()) # Or whatever query you'd like
        
    

        

project_manager/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404,render,redirect
from django.urls import reverse
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from django.urls import reverse,reverse_lazy

from .models import Project,ProjectCreateForm,Task,TaskCreateForm


class ProjectListView(generic.ListView):
    template_name = 'project_manager/index.html'
    context_object_name = 'projects_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Project.objects.order_by('-create_date')[:5]

class CreateProjectView(View):
    form_class    =  ProjectCreateForm
    success_url   =  reverse_lazy('project_manager:index')
    template_name = 'project_manager/create_project.html'

    def get(self, request, *args, **kwargs):
        form_args  = {}
        create_obj = self.form_class(**form_args)
        return render(
            request,
            self.template_name,
            {
                'CreateProjectForm': create_obj
            }
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return redirect(self.success_url)
        else:
            # return render(request, self.template_name, {'form': form})
            form_args = {}
            create_obj = self.form_class(**form_args)
            return render(
                request,
                self.template_name,
                {
                    'CreateProjectForm': create_obj
                }
            )

class EditProjectView(View):
    operating_form   =  ProjectCreateForm
    operating_model  =  Project
    success_url      =  reverse_lazy('project_manager:index')
    template_name    = 'project_manager/create_project.html'

    def get(self, request, project_id):
        row_instance  = self.operating_model.objects.get(id=project_id)
        form_obj      = self.operating_form(instance=row_instance)
        request.session['reverse_project_id'] = project_id
        return render(
            request,
            self.template_name,
            {
                'CreateProjectForm': form_obj
            }
        )

    def post(self, request, *args, **kwargs):
        project_id    = request.session['reverse_project_id']
        row_instance  = self.operating_model.objects.get(id=project_id)
        form          = self.operating_form(request.POST, request.FILES, instance=row_instance)
        if form.is_valid():
            print(" \t - Recieved form was valid.")
            form.save(commit=True)
            del request.session['reverse_project_id']
            return redirect(self.success_url)
        else:
            row_instance  = self.operating_model.objects.get(id=project_id)
            form_obj      = self.operating_form(instance=row_instance)
            return render(
                request,
                self.template_name,
                {
                    'CreateProjectForm': form_obj
                }
            )

class DeleteProjectView(View):
    operating_model = Project
    success_url     = reverse_lazy('project_manager:index')

    def get(self, request, project_id):
        search_query = self.operating_model.objects.get(id= project_id)
        
        search_query.delete()
        return redirect(self.success_url)

class DeleteTaskView(View):
    operating_model  = Task
    success_url      =  'project_manager:project_detail'

    def get(self, request, project_id, task_id):
        search_query = self.operating_model.objects.get(id= task_id)
        search_query.delete()
        success_url  = reverse_lazy(f"{self.success_url}",kwargs={'project_id': project_id})
        return redirect(success_url)

class DetailProjectView(View):
    project_model    =  Project
    task_model       =  Task
    success_url      =  reverse_lazy('project_manager:index')
    template_name    = 'project_manager/project_detail.html'

    def get(self, request, project_id):
        project        = self.project_model.objects.get(id= project_id)
        tasks          = self.task_model.objects.filter(project=project)
        request.session['reverse_project_name'] = project.project_name
        request.session['reverse_project_id'] = project.id
        # print(project_tasks)
        return render(
                request,
                self.template_name,
                {
                    'project': project,
                    'tasks': tasks
                }
            )
        # return redirect(self.success_url)

class CreateTaskView(View):
    form_class    =  TaskCreateForm
    success_url   =  reverse_lazy('project_manager:index')
    template_name = 'project_manager/create_task.html'

    def get(self, request, *args, **kwargs):
        form_args  = {}
        create_obj = self.form_class(**form_args)
        return render(
            request,
            self.template_name,
            {
                'CreateTaskForm': create_obj
            }
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return redirect(self.success_url)
        else:
            # return render(request, self.template_name, {'form': form})
            form_args = {}
            create_obj = self.form_class(**form_args)
            return render(
                request,
                self.template_name,
                {
                    'CreateTaskForm': create_obj
                }
            )

class EditTaskView(View):
    operating_form  =  TaskCreateForm
    operating_model =  Task
    template_name   =  'project_manager/create_task.html'
    success_url     =  'project_manager:project_detail'

    def get(self, request, project_id, task_id):
        my_record  = self.operating_model.objects.get(id=task_id)
        form_obj   = self.operating_form(instance=my_record)

        request.session['reverse_project_id'] = project_id
        request.session['reverse_task_id']    = task_id
        # create_obj = self.form_class(**form_args)
        return render(
            request,
            self.template_name,
            {
                'CreateTaskForm': form_obj
            }
        )

    def post(self, request, *args, **kwargs):
        project_id    = request.session['reverse_project_id']
        task_id       = request.session['reverse_task_id']
        row_instance  = self.operating_model.objects.get(id=task_id)
        form          = self.operating_form(request.POST, request.FILES, instance=row_instance)
        if form.is_valid():
            form.save(commit=True)
            project_id     = request.session['reverse_project_id']
            success_url    = reverse_lazy(f"{self.success_url}",kwargs={'project_id': project_id})
            del request.session['reverse_project_id'], request.session['reverse_task_id']
            return redirect(success_url)
        else:
            # return render(request, self.template_name, {'form': form})
            row_instance  = self.operating_model.objects.get(id=task_id)
            form_obj      = self.operating_form(instance=row_instance)
            return render(
                request,
                self.template_name,
                {
                    'CreateTaskForm': form_obj
                }
            )

project_manager/templates/project_manager/create_project.html
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ CreateProjectForm.media }}            {# Adds date-picker required JS and CSS #}


<div class="container" style="margin-top: 5%">
    <h1> 
        Create Project
    </h1>
        <a href="{% url 'project_manager:index' %}">Home</a>
        <form method="post" enctype="multipart/form-data"  action="{{ request.path }}" >
            {% csrf_token %}
                <table>
                    {{CreateProjectForm}}
                </table>
            <input type="submit" value="Submit Form"/>
        </form>
</div>

project_manager/templates/project_manager/create_task.html
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ CreateTaskForm.media }}            {# Adds date-picker required JS and CSS #}

<div class="container">
    <h1> 
        Create/Edit Task - [{{ request.session.reverse_project_name }}]
    </h1>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'project_manager:index' %}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'project_manager:project_detail' request.session.reverse_project_id %}">
                    {{ request.session.reverse_project_name }}
                </a>
            </li>
        </ol>
    </nav>

    <form method="post" enctype="multipart/form-data"  action="{{ request.path }}">
        {% csrf_token %}
            <table>
                {{CreateTaskForm}}
            </table>
        <input type="submit" value="Submit Form"/>
    </form>
</div>

project_manager/templates/project_manager/index.html
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ CreateProjectForm.media }}            {# Adds date-picker required JS and CSS #}

<div class="container">
    <h1> 
        Project List 
    </h1>
    <div class="d-flex">
        <div class="ml-auto">
            <a href="{% url 'project_manager:create_project' %}">
                <button type="button" class="btn btn-info" style="align: right;">
                    Create New Project
                </button>
            </a>
        </div>
    </div>
    </br>
{% if projects_list %}
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Avatar</th>
            <th scope="col">Project Name</th>
            <th scope="col">Description</th>
            <th scope="col">Detail View</th>
            <th scope="col">Edit Option</th>
            <th scope="col">Delete Option</th>
            </tr>
        </thead>
    <tbody>
    {% for project in projects_list %}
        <tr>
            <th scope="row">
                1
            </th>
            <td> 
                <img src="{{ project.avatar.url}}" width="45" height="40"/>
            </td>
            <td>
                {{ project.project_name }}
            </td>
            <td>
                {{ project.description }}
            </td>
            <td>
               <a href="{% url 'project_manager:project_detail' project.id %}">detail</a>
            </td>
            <td>
               <a href="{% url 'project_manager:edit_project' project.id %}">edit</a>
            </td>
            <td>
               <a href="{% url 'project_manager:delete_project' project.id %}">delete</a>
            </td>
        </tr>   
    {% endfor %}
    </tbody>
    </table>   
{% else %}
    <p>No Projects are available.</p>
{% endif %}
</div>

project_manager/templates/project_manager/project_detail.html
{% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ CreateTaskForm.media }}            {# Adds date-picker required JS and CSS #}

<div class="container">
    <h1> Project Detail - [{{ project.project_name }}]</h1>
    <div class="d-flex">
        <div class="ml-auto">
            <a href="{% url 'project_manager:create_project' %}">
                <button type="button" class="btn btn-info" style="align: right;">
                    Create New Project
                </button>
            </a>
            <a href="{% url 'project_manager:create_task' %}">
                <button type="button" class="btn btn-primary" style="align: right;">
                    Create New Task
                </button>
            </a>
        </div>
    </div>
    </br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'project_manager:index' %}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{{ project.project_name }}</li>
        </ol>
    </nav>
    {% comment %} <div>
        <img src="{{ project.avatar.url}}" width="20" height="20"/>
        <a href="{% url 'project_manager:project_detail' project.id %}">{{ project.project_name }}</a> 
        <a href="{% url 'project_manager:delete_project' project.id %}">delete</a>
        <a href="{% url 'project_manager:edit_project' project.id %}">edit</a>
    </div> {% endcomment %} 
    </br>
        <div class="alert alert-secondary" role="alert">
            <div style=" text-align:right">
                Created at: {{ project.create_date }} | 
                <a href="{% url 'project_manager:edit_project' project.id %}">[edit]</a> | 
                <a href="{% url 'project_manager:delete_project' project.id %}">[delete]</a> | 
            </div>
            <h5 class="alert-heading"> Description</h5>
                <p>{{ project.description }}</p>
                <hr>
            </div>
    </br>
    {% if tasks %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Task Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Edit Option</th>
                    <th scope="col">Delete Option</th>
                </tr>
            </thead>
            <tbody>
        {% for task in tasks %}
            <tr>
                <th scope="row">1</th>
                <td>
                    {{ task.title }}
                </td>
                <td>
                    {{ task.description }}
                </td>
                <td>
                    {{ task.start_date }}
                </td>
                <td>
                    {{ task.end_date }}
                </td>
                <td>
                     <a href="{% url 'project_manager:edit_task' project.id task.id%}">edit</a>
                </td>
                <td>
                    <a href="{% url 'project_manager:delete_task' project.id task.id%}">delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% else %}
        <p>No Task are assigned to this project.</p>
    {% endif %}
</div>